# Generated by Django 5.1.7 on 2025-04-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_remove_place_image_placeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('nature', 'Gamta'), ('history', 'Istorija'), ('culture', 'Kultūra'), ('architecture', 'Architektūra')], default='nature', max_length=20),
        ),
    ]
